[package]

name = "civng"
version = "0.0.1"
authors = [ "Virgil Dupras <hsoft@hardcoded.net>" ]

[[bin]]
name = "civng"
doc = false

[dependencies]
rustty = "0.1.9"
num = "*"
byteorder = "*"
rand = "*"
bitflags = "*"

