[package]

name = "civng"
version = "0.0.1"
authors = [ "Virgil Dupras <hsoft@hardcoded.net>" ]

[[bin]]
name = "civng"
doc = false

[dependencies]
num = "*"
byteorder = "*"
rand = "*"
bitflags = "*"

[dependencies.rustty]
git = "https://github.com/hsoft/rustty.git"
branch = "ui"

